# wdocker vars:

#wd# docker = docker
#wd# name = memcached

#wd# build = {docker} build -t {name} .
#wd# run = {docker} run -d --name {name} {name}

# wdocker commands:

#wd# start: {docker} start {name}
#wd# stop: {docker} stop {name}
#wd# shell: {docker} exec -it {name} bash
#wd# init: {run}

FROM memcached:latest
MAINTAINER John Doe <user@example.org>
