# wdocker vars:

#wd# docker = docker
#wd# name = mysql
#wd# pass = -e MYSQL_ROOT_PASSWORD=root

#wd# build = {docker} build -t {name} .
#wd# run = {docker} run -d {pass} --name {name} {name}

# wdocker commands:

#wd# start: {docker} start {name}
#wd# stop: {docker} stop {name}
#wd# shell: {docker} exec -it {name} bash
##wd# init: {run}

FROM mysql:5.5
MAINTAINER Jane Doe <user@example.org>
